# Generated by Django 6.0.3 on 2026-06-07 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='marketplace/owners/')),
                ('response_rate', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__first_name', 'user__last_name', 'user__username'),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(db_index=True)),
                ('source_type', models.CharField(choices=[('house', 'Rental House'), ('room', 'Guest House Room')], db_index=True, max_length=20)),
                ('source_label', models.CharField(blank=True, max_length=180)),
                ('title', models.CharField(db_index=True, max_length=180)),
                ('property_type', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('location_text', models.CharField(blank=True, db_index=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('district', models.CharField(blank=True, db_index=True, max_length=120)),
                ('village', models.CharField(blank=True, db_index=True, max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('marketplace_enabled', models.BooleanField(db_index=True, default=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='marketplace/properties/')),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating_average', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('guest_capacity', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('wifi', models.BooleanField(db_index=True, default=False)),
                ('parking', models.BooleanField(db_index=True, default=False)),
                ('swimming_pool', models.BooleanField(db_index=True, default=False)),
                ('air_conditioning', models.BooleanField(db_index=True, default=False)),
                ('key_amenities', models.JSONField(blank=True, default=list)),
                ('listed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='marketplace.ownerprofile')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_properties', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-featured', '-listed_at'),
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/properties/gallery/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.property')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('guests', models.PositiveSmallIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('source_booking_reference', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='marketplace.property')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=120)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField(blank=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.property')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['marketplace_enabled', 'featured'], name='marketplace_marketp_bc5f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'district', 'village'], name='marketplace_city_0cb592_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price_from', 'guest_capacity'], name='marketplace_price_f_6f9c7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_object_id'), name='unique_marketplace_source_object'),
        ),
        migrations.AddIndex(
            model_name='propertyreview',
            index=models.Index(fields=['property', 'is_public'], name='marketplace_propert_fdf17b_idx'),
        ),
    ]
