# Generated by Django 6.0.4 on 2026-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinquiry',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('payment_expired', 'Payment Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
