# Generated by Django 6.0.4 on 2026-06-06 20:14

import django.db.models.deletion
import django.utils.timezone
import guesthouse.models.booking
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('room_name', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], db_index=True, default='available', max_length=20)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekend_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional weekend rate (Fri/Sat).', max_digits=10, null=True)),
                ('monthly_price_optional', models.DecimalField(blank=True, decimal_places=2, help_text='Optional monthly rate for long stays.', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='guesthouse/rooms/')),
                ('amenities', models.TextField(blank=True, help_text='Comma separated list of amenities (Wi-Fi, AC, TV, ...).')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('room_number',),
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_capacity', models.PositiveSmallIntegerField(default=2, help_text='How many guests this room type usually accommodates.')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, help_text='Default nightly rate for this room type.', max_digits=10)),
                ('icon', models.CharField(blank=True, help_text='Optional icon class (Bootstrap-icons / Material).', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=80)),
                ('last_name', models.CharField(db_index=True, max_length=80)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('national_id_or_passport', models.CharField(blank=True, db_index=True, max_length=64)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_vip', models.BooleanField(db_index=True, default=False)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_stay_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='guesthouse__last_na_e89ed1_idx'), models.Index(fields=['phone'], name='guesthouse__phone_545928_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, default=guesthouse.models.booking._generate_booking_reference, max_length=32, unique=True)),
                ('booking_source', models.CharField(choices=[('walk_in', 'Walk In'), ('phone', 'Phone'), ('website', 'Website'), ('booking_com', 'Booking.com'), ('airbnb', 'Airbnb'), ('agent', 'Agent'), ('other', 'Other')], db_index=True, default='walk_in', max_length=20)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('check_in_date', models.DateField(db_index=True)),
                ('check_out_date', models.DateField(db_index=True)),
                ('actual_check_in', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out', models.DateTimeField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('nights', models.PositiveIntegerField(default=1)),
                ('room_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, help_text='Any extra charges (minibar, damages, late checkout) added at checkout.', max_digits=10)),
                ('amount_paid', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10)),
                ('special_requests', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='guesthouse.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='guesthouse.room')),
            ],
            options={
                'ordering': ('-check_in_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RoomMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('issue', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('reported_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_maintenance_assigned', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_maintenance_reported', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_issues', to='guesthouse.room')),
            ],
            options={
                'verbose_name': 'Room Maintenance',
                'verbose_name_plural': 'Room Maintenance',
                'ordering': ('-reported_date',),
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='guesthouse.roomtype'),
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_check_in', models.DateTimeField(db_index=True)),
                ('actual_check_out', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('vehicle_registration', models.CharField(blank=True, max_length=40)),
                ('special_requests', models.TextField(blank=True)),
                ('id_document_seen', models.BooleanField(default=False)),
                ('key_card_no', models.CharField(blank=True, max_length=40)),
                ('arrival_notes', models.TextField(blank=True)),
                ('departure_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stay', to='guesthouse.booking')),
            ],
            options={
                'ordering': ('-actual_check_in',),
            },
        ),
        migrations.CreateModel(
            name='GuestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('eft', 'EFT'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], db_index=True, default='cash', max_length=20)),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='guesthouse.booking')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-payment_date', '-created_at'),
                'indexes': [models.Index(fields=['payment_method', 'payment_date'], name='guesthouse__payment_04fa08_idx')],
            },
        ),
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('deep_cleaning', 'Deep Cleaning'), ('inspection', 'Inspection'), ('laundry', 'Laundry')], db_index=True, default='cleaning', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10)),
                ('scheduled_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='guesthouse.room')),
            ],
            options={
                'ordering': ('-scheduled_date', '-created_at'),
                'indexes': [models.Index(fields=['status', 'scheduled_date'], name='guesthouse__status_9f55d9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in_date', 'check_out_date'], name='guesthouse__check_i_e38c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status', 'check_in_date'], name='guesthouse__booking_b14aef_idx'),
        ),
        migrations.AddIndex(
            model_name='roommaintenance',
            index=models.Index(fields=['status', 'priority'], name='guesthouse__status_2b2059_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'active'], name='guesthouse__status_acb2bf_idx'),
        ),
    ]
