# Generated by Django 6.0.4 on 2026-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0004_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_size',
            field=models.CharField(default='1 bedroom', max_length=100),
        ),
    ]
