# Generated by Django 6.0.4 on 2026-06-01 21:25

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0009_smsretrymessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('skills', models.CharField(help_text='Comma-separated skills e.g. plumbing, electrical, carpentry', max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Approved by platform admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('estimated_days', models.PositiveIntegerField(help_text='Estimated days to complete the work')),
                ('notes', models.TextField(blank=True, help_text='Approach, materials, or any clarifications for the landlord')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tennants.issue')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tennants.worker')),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance & Repairs'), ('utilities', 'Utilities (Water/Electricity)'), ('taxes', 'Property Taxes & Levies'), ('insurance', 'Insurance'), ('cleaning', 'Cleaning & Sanitation'), ('security', 'Security'), ('management', 'Management Fees'), ('advertising', 'Advertising & Marketing'), ('supplies', 'Supplies'), ('other', 'Other')], db_index=True, default='maintenance', max_length=20)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, help_text='Who was paid (worker name, utility co., etc.)', max_length=100)),
                ('expense_date', models.DateField(db_index=True, default=datetime.datetime.now)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat_building', models.ForeignKey(blank=True, help_text='Property (building) the expense is for. Optional if house is set.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tennants.flatbuilding')),
                ('house', models.ForeignKey(blank=True, help_text='Specific house (optional, scoped under the building)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tennants.house')),
                ('related_issue', models.ForeignKey(blank=True, help_text='Optional - maintenance issue this expense resolved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='tennants.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('related_bid', models.ForeignKey(blank=True, help_text='Optional - worker bid this expense settled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='tennants.maintenancebid')),
            ],
            options={
                'ordering': ('-expense_date', '-created_at'),
                'indexes': [models.Index(fields=['user', 'expense_date'], name='tennants_ex_user_id_4f6415_idx'), models.Index(fields=['flat_building', 'expense_date'], name='tennants_ex_flat_bu_e6c99a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenancebid',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('issue',), name='unique_accepted_bid_per_issue'),
        ),
    ]
