# Generated by Django 6.0.4 on 2026-06-01 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0010_worker_maintenancebid_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_recoverable',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, this expense will be charged to the tenant (added to their balance).'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_recovered',
            field=models.BooleanField(default=False, help_text='Has the tenant reimbursed this expense?'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recovered_date',
            field=models.DateField(blank=True, help_text='When the tenant reimbursed this expense.', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant-specific expense charged to this tenant (recoverable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='tennants.tenant'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('utilities', 'Utilities (Water/Electricity)'), ('maintenance', 'Maintenance & Repairs'), ('taxes', 'Property Taxes & Levies'), ('insurance', 'Insurance'), ('cleaning', 'Cleaning & Sanitation'), ('security', 'Security'), ('management', 'Management Fees'), ('advertising', 'Advertising & Marketing'), ('supplies', 'Supplies'), ('other', 'Other')], db_index=True, default='maintenance', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='flat_building',
            field=models.ForeignKey(blank=True, help_text='Entire building expense (e.g. water bill, security). Optional if house or tenant is set.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tennants.flatbuilding'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='house',
            field=models.ForeignKey(blank=True, help_text='House-specific expense (e.g. individual electricity meter).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tennants.house'),
        ),
    ]
