# Generated by Django 6.0.4 on 2026-06-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0011_expense_is_recoverable_expense_is_recovered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, help_text='House photo for marketplace and records', null=True, upload_to='houses/'),
        ),
    ]
